### ISSUE TITLE
Nice man

### ISSUE THREAD

**Issue by GuyTheDeveloper** [JumaboyevJasurbek/LinCore-project#48]
https://github.com/JumaboyevJasurbek/LinCore-project/blob/b7a2b17a9ea0dcb9641d4cbe063fafd3834d5b0d/tsconfig.json#L2

**Comment by GuyTheDeveloper** [comment]
bomba

**Comment by GuyTheDeveloper** [comment]
e kelinchakdek ochaverar ekanda

**Comment by JumaboyevJasurbek** [comment]
Can you write in English?
